' Gambas module file

'
' GauchoCAD
' Rapid Application Development for Gambas
'
' Copyright (C) Martín Belmonte
'
' This program is free software; you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation; either version 2 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program; if not, write to the Free Software
' Foundation, Inc., 51 Franklin St, Fifth Floor,
' Boston, MA  02110-1301  USA
'
' Variables a transferir
Private adi As String               '' Directorio del programa
Private apc As String               '' Archivo de configuracion del programa
Private CADConfig As String         '' CAD config file
Private etx As String               '' Editor de texto plano por defecto
Private lgf As String               '' Archivo de registro de incidencias
'Private dbn As String               '' Nombre de la base de datos
'Private sql As String               '' Sentencia SQL de creacion de la base de datos varia segun el tipo de base de datos.
Private lgg As Logger               '' Registro de eventos de la aplicación.

' Global vars
Public sFonts As String             '' Fonts directory
Public sTextures As String          '' Textures directory
Public gColor As New Integer[]      '' Colors list
'Tincho
'Vars direct or derivated from config xml
Public flgWindowBackColor As Integer '= Color.Blac  '' Window backgrount color
Public flgWindowTextColor As Integer   '' Window helper text color
Public flgWindowCursorColor As Integer '' Window cursor color
Public flgWhiteAndBlack As Integer     '' El color blanco/negro siempre sera distinto al

''Vars for environment
Public flgWindowMode As Integer
Public flgWindowInfoColor As Integer           ' habria que agrupar todas las vars de ambiente, hay dos opciones simples

'----------------------
Public cCommands As New Collection   '' Commands list
Public cColors As New Collection     '' Colors list
Public ColorsRGB As New String[]     '' Colors lists each item as r,g,b string
Public cLtypes As New Collection     '' Linetypes list

' Variables de un solo uso
Private ldd As Boolean              '' Testigo de finalización de carga.

Public Sub Main()

  Run

  gcd.Main

  APPMain.Workspace1.ActiveWindow.SetFocus

End

Public Sub Run()

  '    Dim sFile As String
  Dim cex As New Collection         '' Colección con variables para pasar al siguiente módulo o formulario
  '    Dim rpl As New Collection         '' Lista de nombres de tablas y campos y sus titulos para reemplazar nombres por titulos en el xml cuando es creado
  Dim thx As New String[]           '' Lista d etemas del editor interno
  Dim i As Integer
  Dim CADConfigData As New Collection

  '' Verificar que existe el direcotrio del porgrama en Home
  adi = User.Home &/ "." & String.LCase(vag.NoSymbols(Application.Title))
  sFonts = adi &/ "fonts/lfe"
  sTextures = adi &/ "textures"

  apc = adi &/ "cfg.xml"
  lgf = adi &/ Format(Now(), "yyyy") & ".log"

  If Exist(adi) = False Then
    Shell "mkdir -p " & adi Wait
  Endif

  If Exist(sFonts) = False Then
    Shell "mkdir -p " & sFonts Wait
  Endif

  thx.Clear
  thx = fil.RListFiles("./fonts/lfe", ["lff"])

  If thx.Count > 0 Then
    For i = 0 To thx.Max
      If Exist(thx[i]) Then
        If Exist(sFonts &/ File.Name(thx[i])) = False Then
          Copy thx[i] To sFonts &/ File.Name(thx[i])
        Endif
      Endif
    Next
  Endif

  If Exist(sTextures) = False Then
    Shell "mkdir -p " & sTextures Wait
  Endif

  thx.Clear
  thx = fil.RListFiles("./textures", ["jpg", "jpeg", "png"])

  If thx.Count > 0 Then
    For i = 0 To thx.Max
      If Exist(thx[i]) Then
        If Exist(sTextures &/ File.Name(thx[i])) = False Then
          Copy thx[i] To sTextures &/ File.Name(thx[i])
        Endif
      Endif
    Next
  Endif

  '' Estableciendo las variables de entorno especiales con un archivo XML
  CADConfig = adi &/ "cad.xml"
  ' If Exist(File.Dir(CADConfig)) = False Then
  '     Mkdir File.Dir(CADConfig)
  ' Endif
  ' If Exist(CADConfig) = False Then
  '     CADConfigData = cad.CADConfig()
  '     xmg.XmlConfMaker(CADConfig, CADConfigData, Application.Title & " " & Application.Version)
  ' Endif

  '' Arrancando el sistema de
  If Exist(lgf) = False Then
    Shell "touch " & lgf Wait
  Endif
  lgg = New Logger(Logger.Info, Logger.DefaultFormat, lgf)
  lgg.Begin

  '' Verificación del editor de texto plano por defecto en el sistema
  If sog.MimeDefaultApp("text/plain").Count > 0 Then
    etx = sog.MimeDefaultApp("text/plain")[0]
  Else
    etx = ""
  Endif

  '' Bandera de indicacion de formulario cargado
  ldd = True

  '' Applying the environments vars
  SetEnvironmentVars()

  '' Load the commands list
  cCommands = LoadCommandsList()

  '' Load the colors list
  cColors = LoadColors()
  ColorsRGB = cad.RGBColors()

  '' Load the linetypes list
  cLtypes = LoadLtypes()

  gcolor = cad.DecodeColor()

  ' corrijo los colores que no se ven contra el fondo
  gcolor[0] = flgWhiteAndBlack
  gcolor[7] = flgWhiteAndBlack
  gcolor[255] = flgWhiteAndBlack

  '' Abrir el formulario principal del programa
  cex.Add(adi, "AppDir")
  cex.Add(apc, "AppCfg")
  cex.Add(CADConfig, "CADCfg")
  cex.Add(etx, "AppEdi")
  cex.Add(lgg, "AppLog")

  APPMain.Run(cex)
  'FCAD.Run(cex)

End

Private Sub SetEnvironmentVars()

  ' '' Vars for form interface
  ' Select xmg.GetVar("Application.window-background-color", apc)
  '         ''DEPRECATED: Cambiar en la proxima version de gambas para usar la propiedad .DarkTheme
  '
  '     Case "Light"
  '         flgWindowBackColor = Color.White
  '         flgWindowInfoColor = &HFFFF00
  '         flgWindowTextColor = Color.Blue
  '         flgWindowCursorColor = Color.Black
  '     Case Else
  '         flgWindowBackColor = Color.Black
  '         flgWindowInfoColor = &HA0A000
  '         flgWindowTextColor = Color.Yellow
  '         flgWindowCursorColor = Color.White
  ' End Select

  ''Vars for OpenGL window
  Select xmg.GetVar("CAD.Background-Dark", apc)

    Case True
      flgWindowBackColor = Color.White
      flgWindowInfoColor = &HFFFF00
      flgWindowTextColor = Color.Blue
      flgWindowCursorColor = Color.Black
      flgWhiteAndBlack = Color.Black

    Case Else
      flgWindowBackColor = Color.Black
      flgWindowInfoColor = &HA0A000
      flgWindowTextColor = Color.Yellow
      flgWindowCursorColor = Color.White
      flgWhiteAndBlack = Color.White

  End Select

End

Private Function LoadCommandsList() As Collection

  Dim cComm As New Collection

  cComm.Add(["chamfer", "cd"], "chamfer")
  cComm.Add(["copy", "c"], "copy")
  cComm.Add(["divide", "dx"], "divide")
  cComm.Add(["erase", "de"], "erase")
  cComm.Add(["extend", "e"], "extend")
  cComm.Add(["fillet", "f"], "fillet")
  cComm.Add(["mirror", "mn"], "mirror")
  cComm.Add(["move", "m"], "move")
  cComm.Add(["offset", "fg"], "offset")
  cComm.Add(["pan", "zc"], "pan")
  cComm.Add(["rotate", "rt"], "rotate")
  cComm.Add(["scale", "sc"], "scale")
  cComm.Add(["stretch", "s"], "stretch")
  cComm.Add(["trim", "tr"], "trim")
  cComm.Add(["zoome", "zx"], "zoome")
  cComm.Add(["zoomw", "z"], "zoomw")

  cComm.Add(["arc", "a"], "arc")
  cComm.Add(["circle", "cv"], "circle")
  cComm.Add(["dim", "dw"], "dim")
  cComm.Add(["ellipse", "ew"], "ellipse")
  cComm.Add(["hatch", "ht"], "hatch")
  cComm.Add(["insert", "b"], "insert")
  cComm.Add(["leader", "li"], "leader")
  cComm.Add(["line", "l"], "line")
  cComm.Add(["mtext", "tt"], "mtext")
  cComm.Add(["pline", "po"], "pline")
  cComm.Add(["rectangle", "re"], "rectangle")
  cComm.Add(["solid", "sa"], "solid")
  cComm.Add(["spline", "sq"], "spline")
  cComm.Add(["text", "t"], "text")

  cComm.Add(["beam", "w1"], "beam")
  cComm.Add(["column", "w2"], "column")
  cComm.Add(["slab3p", "w3"], "slab3p")
  cComm.Add(["slab4p", "w4"], "slab4p")
  cComm.Add(["wallcolumn", "w5"], "wallcolumn")

  cComm.Add(["layers", "lk"], "layers")

  Return cComm

End

Private Function LoadColors() As Collection

  Dim cColor As New Collection

  cColor.Add(["ByBlock", 0], "0")
  cColor.Add(["ByLayer", 256], "256")
  cColor.Add([("Red"), 1], "1")
  cColor.Add([("Yellow"), 2], "2")
  cColor.Add([("Green"), 3], "3")
  cColor.Add([("Cyan"), 4], "4")
  cColor.Add([("Blue"), 5], "5")
  cColor.Add([("Magenta"), 6], "6")
  cColor.Add([("White"), 7], "7")

  Return cColor

End

Public Function LoadLtypes() As Collection

  Dim lty As New Collection

  lty.Add([[3], "Continous"], "0") '1
  lty.Add([[14, 4, 4, 4], "Center"], "1") '1
  lty.Add([[10, 6, 3, 6], "Dashdot"], "2") '2
  lty.Add([[10, 6], "Dashed"], "3") '3
  lty.Add([[6, 4, 3, 4, 3, 4], "Divide"], "4") '4
  lty.Add([[3, 4], "Dot"], "5") '6
  lty.Add([[6, 4], "Hidden"], "6") '7
  lty.Add([[4, 3], "Hidden2"], "7") '8
  lty.Add([[12, 4, 4, 4, 4, 4], "Phantom"], "8") '9
  lty.Add([[3], "ByBLock"], "9") '1
  lty.Add([[3], "ByLayer"], "10") '1

  Return lty

End
