# Gambas Action File 3.0

{ Actions
  { Action cadBeam
    Text = "Beam"
    Picture = "$ToggleButton"
  }
  { Action cadCWall
    Text = "CWall"
    Picture = "$ToggleButton"
  }
  { Action cadCircle
    Text = "Circle"
    Picture = "png/32x32/menucircle.png"
  }
  { Action cadColumn
    Text = "Column"
    Picture = "$ToggleButton"
  }
  { Action cadDim
    Text = "Dim"
    Picture = "png/32x32/cotas.png"
  }
  { Action cadEllipse
    Text = "Ellipse"
    Picture = "png/32x32/menuellipse.png"
  }
  { Action cadLantern
    Text = "Lantern"
    Picture = "$ToggleButton"
  }
  { Action cadLine
    Text = "Line"
    Picture = "png/32x32/menuline.png"
  }
  { Action cadPLine
    Text = "pLine"
    Picture = "png/32x32/pline.png"
  }
  { Action cadRectangle
    Text = "Rectangle"
    Picture = "svg/circle.svg"
  }
  { Action cadShellball
    Text = "Shellball"
    Picture = "$ToggleButton"
  }
  { Action cadText
    Text = "Text"
    Picture = "png/32x32/menutext.png"
  }
}

